# Generated by Django 5.1.1 on 2024-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='price',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
