# Generated by Django 5.1.1 on 2024-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_pets_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
    ]
