# Generated by Django 5.1.1 on 2024-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_cust_register_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_register',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
