# Generated by Django 5.1.1 on 2024-10-10 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_cust_register_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.cust_register')),
            ],
        ),
    ]
